server:
  port: 8082

# 注册到 admin-server 8081
spring:
  boot:
    admin:
      client:
        url: http://127.0.0.1:9001
  application:
    name: admin-client
# web端点暴露
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
